using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusServiceMarketingSystem.Models.Common;
using NexusServiceMarketingSystem.Models.Entities;
using NexusServiceMarketingSystem.Models.Enums;

namespace NexusServiceMarketingSystem.Data.Configurations
{
    /// <summary>Table: Connections.</summary>
    public class ConnectionConfiguration : IEntityTypeConfiguration<Connection>
    {
        public void Configure(EntityTypeBuilder<Connection> builder)
        {
            builder.ToTable("Connections", t =>
            {
                t.HasCheckConstraint("CK_Connections_ConnectionType_Letter", ConfigurationHelpers.ConnectionTypeLetter("ConnectionType"));
                t.HasCheckConstraint("CK_Connections_Status_Values", ConfigurationHelpers.EnumInList<ConnectionStatus>("Status"));

                // EXACTLY 16 characters: D/B/T + 3 city digits + 12 serial digits. Case-sensitive.
                t.HasCheckConstraint("CK_Connections_AccountId_Format",
                    ConfigurationHelpers.ExactLike("AccountId", IdentifierFormat.AccountIdLikePattern));

                // The first letter of the account ID must be the connection's own type.
                t.HasCheckConstraint("CK_Connections_AccountId_Type", "LEFT([AccountId], 1) = [ConnectionType]");

                t.HasCheckConstraint("CK_Connections_Deposit", "[SecurityDepositAmount] >= 0");
            });

            builder.HasKey(c => c.Id);

            // The account ID is generated by the system and never entered by a user.
            builder.Property(c => c.AccountId).IsRequired().HasColumnType("char(16)");
            builder.Property(c => c.ConnectionType).IsRequired().HasConnectionTypeCode();
            builder.Property(c => c.InstallationAddress).IsRequired().HasMaxLength(300);
            builder.Property(c => c.PhoneNumber).HasMaxLength(20);
            builder.Property(c => c.Status).IsRequired().HasStringConversion();
            builder.Property(c => c.SecurityDepositAmount).HasPrecision(18, 2);
            builder.Property(c => c.ActivatedAtUtc).HasDefaultValueSql("SYSUTCDATETIME()");
            builder.Property(c => c.StatusChangedAtUtc).HasDefaultValueSql("SYSUTCDATETIME()");
            builder.Property(c => c.RowVersion).IsRowVersion();

            // ---- Relationships (all RESTRICT) ----
            builder.HasOne(c => c.Order)
                   .WithMany(o => o.Connections)
                   .HasForeignKey(c => c.OrderId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(c => c.Customer)
                   .WithMany(cu => cu.Connections)
                   .HasForeignKey(c => c.CustomerId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(c => c.Plan)
                   .WithMany(p => p.Connections)
                   .HasForeignKey(c => c.PlanId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(c => c.City)
                   .WithMany()
                   .HasForeignKey(c => c.CityId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(c => c.CreatedByEmployee)
                   .WithMany()
                   .HasForeignKey(c => c.CreatedByEmployeeId)
                   .OnDelete(DeleteBehavior.Restrict);

            // Dial-up connections point at their landline connection (self-reference).
            builder.HasOne(c => c.LandlineConnection)
                   .WithMany()
                   .HasForeignKey(c => c.LandlineConnectionId)
                   .OnDelete(DeleteBehavior.Restrict);

            // ---- Indexes ----
            // The account ID is the public lookup key, so it must be unique.
            builder.HasIndex(c => c.AccountId).IsUnique().HasDatabaseName("UX_Connections_AccountId");

            // Search by status / type.
            builder.HasIndex(c => c.Status).HasDatabaseName("IX_Connections_Status");
            builder.HasIndex(c => c.ConnectionType).HasDatabaseName("IX_Connections_ConnectionType");
            builder.HasIndex(c => c.ActivatedAtUtc).HasDatabaseName("IX_Connections_ActivatedAtUtc");
        }
    }
}
