using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NexusServiceMarketingSystem.Models.Common;
using NexusServiceMarketingSystem.Models.Entities;
using NexusServiceMarketingSystem.Models.Enums;

namespace NexusServiceMarketingSystem.Data.Configurations
{
    /// <summary>Table: Orders.</summary>
    public class OrderConfiguration : IEntityTypeConfiguration<Order>
    {
        public void Configure(EntityTypeBuilder<Order> builder)
        {
            builder.ToTable("Orders", t =>
            {
                t.HasCheckConstraint("CK_Orders_ConnectionType_Letter", ConfigurationHelpers.ConnectionTypeLetter("ConnectionType"));
                t.HasCheckConstraint("CK_Orders_Status_Values", ConfigurationHelpers.EnumInList<OrderStatus>("Status"));

                // EXACTLY 11 characters: D/B/T followed by ten digits. Case-sensitive (binary collation).
                t.HasCheckConstraint("CK_Orders_OrderNumber_Format",
                    ConfigurationHelpers.ExactLike("OrderNumber", IdentifierFormat.OrderNumberLikePattern));

                // The first letter of the order number must be the order's own connection type.
                t.HasCheckConstraint("CK_Orders_OrderNumber_Type", "LEFT([OrderNumber], 1) = [ConnectionType]");

                t.HasCheckConstraint("CK_Orders_Quantity", "[Quantity] >= 1");
                t.HasCheckConstraint("CK_Orders_DiscountPercent", "[DiscountPercent] >= 0 AND [DiscountPercent] <= 100");
            });

            builder.HasKey(o => o.Id);

            // The order number is generated by the system and never entered by a user.
            builder.Property(o => o.OrderNumber).IsRequired().HasColumnType("char(11)");
            builder.Property(o => o.ConnectionType).IsRequired().HasConnectionTypeCode();
            builder.Property(o => o.InstallationAddress).IsRequired().HasMaxLength(300);
            builder.Property(o => o.Quantity).IsRequired();
            builder.Property(o => o.DiscountPercent).HasPrecision(5, 2);
            builder.Property(o => o.Status).IsRequired().HasStringConversion();
            builder.Property(o => o.PlacedAtUtc).HasDefaultValueSql("SYSUTCDATETIME()");
            builder.Property(o => o.StatusChangedAtUtc).HasDefaultValueSql("SYSUTCDATETIME()");
            builder.Property(o => o.Remarks).HasMaxLength(500);
            builder.Property(o => o.RowVersion).IsRowVersion();

            // ---- Relationships (all RESTRICT: business records are never deleted by cascade) ----
            builder.HasOne(o => o.Customer)
                   .WithMany(c => c.Orders)
                   .HasForeignKey(o => o.CustomerId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(o => o.Plan)
                   .WithMany(p => p.Orders)
                   .HasForeignKey(o => o.PlanId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(o => o.City)
                   .WithMany()
                   .HasForeignKey(o => o.CityId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(o => o.RetailShop)
                   .WithMany(s => s.Orders)
                   .HasForeignKey(o => o.RetailShopId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(o => o.PlacedByEmployee)
                   .WithMany()
                   .HasForeignKey(o => o.PlacedByEmployeeId)
                   .OnDelete(DeleteBehavior.Restrict);

            builder.HasOne(o => o.DiscountScheme)
                   .WithMany(d => d.Orders)
                   .HasForeignKey(o => o.DiscountSchemeId)
                   .OnDelete(DeleteBehavior.Restrict);

            // ---- Indexes ----
            // The order number is the public lookup key, so it must be unique.
            builder.HasIndex(o => o.OrderNumber).IsUnique().HasDatabaseName("UX_Orders_OrderNumber");

            // Advanced search: by type, status and date / period.
            builder.HasIndex(o => o.ConnectionType).HasDatabaseName("IX_Orders_ConnectionType");
            builder.HasIndex(o => o.Status).HasDatabaseName("IX_Orders_Status");
            builder.HasIndex(o => o.PlacedAtUtc).HasDatabaseName("IX_Orders_PlacedAtUtc");
        }
    }
}
