// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusServiceMarketingSystem.Data;

#nullable disable

namespace NexusServiceMarketingSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260930134834_VendorProductPurchases")]
    partial class VendorProductPurchases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("GeneratedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<decimal>("PlanCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ReplacementCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SecurityDepositCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceTaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServiceTaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UsageCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("IX_Bills_DueDate");

                    b.HasIndex("GeneratedByEmployeeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Bills_Status");

                    b.HasIndex("ConnectionId", "PeriodStart")
                        .IsUnique()
                        .HasDatabaseName("UX_Bills_Connection_Period");

                    b.ToTable("Bills", null, t =>
                        {
                            t.HasCheckConstraint("CK_Bills_Amounts_NonNegative", "[PlanCharge] >= 0 AND [UsageCharge] >= 0 AND [SecurityDepositCharge] >= 0 AND [ReplacementCharge] >= 0 AND [DiscountAmount] >= 0 AND [SubTotal] >= 0 AND [ServiceTaxAmount] >= 0 AND [TotalAmount] >= 0");

                            t.HasCheckConstraint("CK_Bills_DueDate", "[DueDate] >= [IssueDate]");

                            t.HasCheckConstraint("CK_Bills_Period", "[PeriodEnd] >= [PeriodStart]");

                            t.HasCheckConstraint("CK_Bills_Status_Values", "[Status] IN ('Issued', 'PartiallyPaid', 'Paid', 'Cancelled')");

                            t.HasCheckConstraint("CK_Bills_TaxRate", "[ServiceTaxRate] >= 0 AND [ServiceTaxRate] <= 100");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_Code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Cities_Name");

                    b.ToTable("Cities", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cities_Code_Format", "[Code] COLLATE Latin1_General_100_BIN2 LIKE '[0-9][0-9][0-9]'");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Connection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("char(16)");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("CreatedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("InstallationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("LandlineConnectionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SecurityDepositAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("UX_Connections_AccountId");

                    b.HasIndex("ActivatedAtUtc")
                        .HasDatabaseName("IX_Connections_ActivatedAtUtc");

                    b.HasIndex("CityId");

                    b.HasIndex("ConnectionType")
                        .HasDatabaseName("IX_Connections_ConnectionType");

                    b.HasIndex("CreatedByEmployeeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LandlineConnectionId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Connections_Status");

                    b.ToTable("Connections", null, t =>
                        {
                            t.HasCheckConstraint("CK_Connections_AccountId_Format", "[AccountId] COLLATE Latin1_General_100_BIN2 LIKE '[DBT][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Connections_AccountId_Type", "LEFT([AccountId], 1) = [ConnectionType]");

                            t.HasCheckConstraint("CK_Connections_ConnectionType_Letter", "[ConnectionType] COLLATE Latin1_General_100_BIN2 LIKE '[DBT]'");

                            t.HasCheckConstraint("CK_Connections_Deposit", "[SecurityDepositAmount] >= 0");

                            t.HasCheckConstraint("CK_Connections_Status_Values", "[Status] IN ('Active', 'TemporarilyInactive', 'PermanentlyInactive')");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.ConnectionProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReplacement")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReturnedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("ProductId", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_ConnectionProducts_Product_Serial")
                        .HasFilter("[SerialNumber] IS NOT NULL");

                    b.ToTable("ConnectionProducts", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConnectionProducts_Quantity", "[Quantity] >= 1");

                            t.HasCheckConstraint("CK_ConnectionProducts_Returned", "[ReturnedAtUtc] IS NULL OR [ReturnedAtUtc] >= [IssuedAtUtc]");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Customers_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("FullName")
                        .HasDatabaseName("IX_Customers_FullName");

                    b.HasIndex("Phone")
                        .HasDatabaseName("IX_Customers_Phone");

                    b.ToTable("Customers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Customers_Corporate_Company", "[CustomerType] <> 'Corporate' OR [CompanyName] IS NOT NULL");

                            t.HasCheckConstraint("CK_Customers_CustomerType_Values", "[CustomerType] IN ('Individual', 'Corporate')");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.DiscountScheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppliesToAdvance")
                        .HasColumnType("bit");

                    b.Property<bool>("AppliesToSecurityDeposit")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxConnections")
                        .HasColumnType("int");

                    b.Property<int>("MinConnections")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MinConnections")
                        .IsUnique()
                        .HasDatabaseName("UX_DiscountSchemes_Min");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_DiscountSchemes_Name");

                    b.ToTable("DiscountSchemes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiscountSchemes_Percent", "[DiscountPercent] >= 0 AND [DiscountPercent] <= 100");

                            t.HasCheckConstraint("CK_DiscountSchemes_Range", "[MinConnections] >= 1 AND ([MaxConnections] IS NULL OR [MaxConnections] >= [MinConnections])");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliesToAdvance = true,
                            AppliesToSecurityDeposit = true,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 25m,
                            IsActive = true,
                            MaxConnections = 14,
                            MinConnections = 10,
                            Name = "Bulk 10 to 14 connections"
                        },
                        new
                        {
                            Id = 2,
                            AppliesToAdvance = true,
                            AppliesToSecurityDeposit = true,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 50m,
                            IsActive = true,
                            MaxConnections = 24,
                            MinConnections = 15,
                            Name = "Bulk 15 to 24 connections"
                        },
                        new
                        {
                            Id = 3,
                            AppliesToAdvance = true,
                            AppliesToSecurityDeposit = true,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 75m,
                            IsActive = true,
                            MaxConnections = 49,
                            MinConnections = 25,
                            Name = "Bulk 25 to 49 connections"
                        },
                        new
                        {
                            Id = 4,
                            AppliesToAdvance = true,
                            AppliesToSecurityDeposit = true,
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountPercent = 100m,
                            IsActive = true,
                            MinConnections = 50,
                            Name = "Bulk 50 or more connections"
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("RetailShopId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Employees_Email");

                    b.HasIndex("RetailShopId");

                    b.ToTable("Employees", null, t =>
                        {
                            t.HasCheckConstraint("CK_Employees_Role_Shop", "([Role] = 'RetailStaff' AND [RetailShopId] IS NOT NULL) OR ([Role] <> 'RetailStaff' AND [RetailShopId] IS NULL)");

                            t.HasCheckConstraint("CK_Employees_Role_Values", "[Role] IN ('Admin', 'Accounts', 'Technical', 'RetailStaff')");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.FeasibilityCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("CheckedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CheckedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<decimal?>("DistanceKm")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("ServerAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByEmployeeId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_FeasibilityChecks_Status");

                    b.HasIndex("OrderId", "CheckType")
                        .IsUnique()
                        .HasDatabaseName("UX_FeasibilityChecks_Order_Type");

                    b.ToTable("FeasibilityChecks", null, t =>
                        {
                            t.HasCheckConstraint("CK_FeasibilityChecks_CheckType_Values", "[CheckType] IN ('Landline', 'Internet')");

                            t.HasCheckConstraint("CK_FeasibilityChecks_Distance", "[DistanceKm] IS NULL OR [DistanceKm] >= 0");

                            t.HasCheckConstraint("CK_FeasibilityChecks_Status_Values", "[Status] IN ('Pending', 'Feasible', 'NotFeasible')");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ConnectionId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SubmittedAtUtc")
                        .HasDatabaseName("IX_Feedbacks_SubmittedAtUtc");

                    b.ToTable("Feedbacks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Feedbacks_Rating", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.IdentifierCounter", b =>
                {
                    b.Property<string>("Scope")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<long>("LastValue")
                        .HasColumnType("bigint");

                    b.HasKey("Scope");

                    b.ToTable("IdentifierCounters", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdentifierCounters_LastValue", "[LastValue] >= 0");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("DiscountSchemeId")
                        .HasColumnType("int");

                    b.Property<string>("InstallationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("char(11)");

                    b.Property<DateTime>("PlacedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("PlacedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RetailShopId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("StatusChangedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("ConnectionType")
                        .HasDatabaseName("IX_Orders_ConnectionType");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DiscountSchemeId");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Orders_OrderNumber");

                    b.HasIndex("PlacedAtUtc")
                        .HasDatabaseName("IX_Orders_PlacedAtUtc");

                    b.HasIndex("PlacedByEmployeeId");

                    b.HasIndex("PlanId");

                    b.HasIndex("RetailShopId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Orders_Status");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_ConnectionType_Letter", "[ConnectionType] COLLATE Latin1_General_100_BIN2 LIKE '[DBT]'");

                            t.HasCheckConstraint("CK_Orders_DiscountPercent", "[DiscountPercent] >= 0 AND [DiscountPercent] <= 100");

                            t.HasCheckConstraint("CK_Orders_OrderNumber_Format", "[OrderNumber] COLLATE Latin1_General_100_BIN2 LIKE '[DBT][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'");

                            t.HasCheckConstraint("CK_Orders_OrderNumber_Type", "LEFT([OrderNumber], 1) = [ConnectionType]");

                            t.HasCheckConstraint("CK_Orders_Quantity", "[Quantity] >= 1");

                            t.HasCheckConstraint("CK_Orders_Status_Values", "[Status] IN ('Placed', 'UnderFeasibilityCheck', 'Feasible', 'NotFeasible', 'Connected', 'Cancelled')");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("PaidAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("ReceivedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RetailShopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PaidAtUtc")
                        .HasDatabaseName("IX_Payments_PaidAtUtc");

                    b.HasIndex("ReceivedByEmployeeId");

                    b.HasIndex("RetailShopId");

                    b.ToTable("Payments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_Method_Values", "[Method] IN ('Cash', 'Card', 'BankTransfer', 'Cheque', 'Online')");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConnectionType")
                        .IsRequired()
                        .HasColumnType("char(1)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("IncludedHours")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("LocalCallRatePerMinute")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal?>("MobileMessagingRatePerMinute")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecurityDeposit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SpeedKbps")
                        .HasColumnType("int");

                    b.Property<decimal?>("StdCallRatePerMinute")
                        .HasPrecision(10, 4)
                        .HasColumnType("decimal(10,4)");

                    b.Property<int>("ValidityMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionType")
                        .HasDatabaseName("IX_Plans_ConnectionType");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Plans_Name");

                    b.ToTable("Plans", null, t =>
                        {
                            t.HasCheckConstraint("CK_Plans_Amounts", "[ValidityMonths] > 0 AND [Price] >= 0 AND [SecurityDeposit] >= 0");

                            t.HasCheckConstraint("CK_Plans_ConnectionType_Letter", "[ConnectionType] COLLATE Latin1_General_100_BIN2 LIKE '[DBT]'");

                            t.HasCheckConstraint("CK_Plans_Hourly_Hours", "[Kind] <> 'Hourly' OR ([IncludedHours] IS NOT NULL AND [IncludedHours] > 0)");

                            t.HasCheckConstraint("CK_Plans_Kind_Matches_Type", "([Kind] IN ('LocalRental', 'StdRental') AND [ConnectionType] = 'T') OR ([Kind] IN ('Hourly', 'Unlimited') AND [ConnectionType] IN ('D', 'B'))");

                            t.HasCheckConstraint("CK_Plans_Kind_Values", "[Kind] IN ('Hourly', 'Unlimited', 'LocalRental', 'StdRental')");

                            t.HasCheckConstraint("CK_Plans_Unlimited_Speed", "[Kind] <> 'Unlimited' OR ([SpeedKbps] IS NOT NULL AND [SpeedKbps] > 0)");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncludedHours = 10,
                            IsActive = true,
                            Kind = "Hourly",
                            Name = "Dial-Up Hourly 10 Hrs",
                            Price = 50m,
                            SecurityDeposit = 325m,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 2,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncludedHours = 30,
                            IsActive = true,
                            Kind = "Hourly",
                            Name = "Dial-Up Hourly 30 Hrs",
                            Price = 130m,
                            SecurityDeposit = 325m,
                            ValidityMonths = 3
                        },
                        new
                        {
                            Id = 3,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncludedHours = 60,
                            IsActive = true,
                            Kind = "Hourly",
                            Name = "Dial-Up Hourly 60 Hrs",
                            Price = 260m,
                            SecurityDeposit = 325m,
                            ValidityMonths = 6
                        },
                        new
                        {
                            Id = 4,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Dial-Up Unlimited 28 Kbps Monthly",
                            Price = 75m,
                            SecurityDeposit = 325m,
                            SpeedKbps = 28,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 5,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Dial-Up Unlimited 28 Kbps Quarterly",
                            Price = 150m,
                            SecurityDeposit = 325m,
                            SpeedKbps = 28,
                            ValidityMonths = 3
                        },
                        new
                        {
                            Id = 6,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Dial-Up Unlimited 56 Kbps Monthly",
                            Price = 100m,
                            SecurityDeposit = 325m,
                            SpeedKbps = 56,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 7,
                            ConnectionType = "D",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Dial-Up Unlimited 56 Kbps Quarterly",
                            Price = 180m,
                            SecurityDeposit = 325m,
                            SpeedKbps = 56,
                            ValidityMonths = 3
                        },
                        new
                        {
                            Id = 8,
                            ConnectionType = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncludedHours = 30,
                            IsActive = true,
                            Kind = "Hourly",
                            Name = "Broadband Hourly 30 Hrs",
                            Price = 175m,
                            SecurityDeposit = 500m,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 9,
                            ConnectionType = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IncludedHours = 60,
                            IsActive = true,
                            Kind = "Hourly",
                            Name = "Broadband Hourly 60 Hrs",
                            Price = 315m,
                            SecurityDeposit = 500m,
                            ValidityMonths = 6
                        },
                        new
                        {
                            Id = 10,
                            ConnectionType = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Broadband Unlimited 64 Kbps Monthly",
                            Price = 225m,
                            SecurityDeposit = 500m,
                            SpeedKbps = 64,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 11,
                            ConnectionType = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Broadband Unlimited 64 Kbps Quarterly",
                            Price = 400m,
                            SecurityDeposit = 500m,
                            SpeedKbps = 64,
                            ValidityMonths = 3
                        },
                        new
                        {
                            Id = 12,
                            ConnectionType = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Broadband Unlimited 128 Kbps Monthly",
                            Price = 350m,
                            SecurityDeposit = 500m,
                            SpeedKbps = 128,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 13,
                            ConnectionType = "B",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "Unlimited",
                            Name = "Broadband Unlimited 128 Kbps Quarterly",
                            Price = 445m,
                            SecurityDeposit = 500m,
                            SpeedKbps = 128,
                            ValidityMonths = 3
                        },
                        new
                        {
                            Id = 14,
                            ConnectionType = "T",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "LocalRental",
                            LocalCallRatePerMinute = 0.55m,
                            Name = "Landline Local Unlimited (Yearly rental)",
                            Price = 75m,
                            SecurityDeposit = 250m,
                            ValidityMonths = 12
                        },
                        new
                        {
                            Id = 15,
                            ConnectionType = "T",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "LocalRental",
                            LocalCallRatePerMinute = 0.75m,
                            Name = "Landline Local Monthly",
                            Price = 35m,
                            SecurityDeposit = 250m,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 16,
                            ConnectionType = "T",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "StdRental",
                            LocalCallRatePerMinute = 0.70m,
                            MobileMessagingRatePerMinute = 1.00m,
                            Name = "Landline STD Monthly",
                            Price = 125m,
                            SecurityDeposit = 250m,
                            StdCallRatePerMinute = 2.25m,
                            ValidityMonths = 1
                        },
                        new
                        {
                            Id = 17,
                            ConnectionType = "T",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Kind = "StdRental",
                            LocalCallRatePerMinute = 0.60m,
                            MobileMessagingRatePerMinute = 1.15m,
                            Name = "Landline STD Half-Yearly",
                            Price = 420m,
                            SecurityDeposit = 250m,
                            StdCallRatePerMinute = 2.00m,
                            ValidityMonths = 6
                        },
                        new
                        {
                            Id = 18,
                            ConnectionType = "T",
                            CreatedAtUtc = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "PRICE NOT GIVEN IN THE PROJECT SPECIFICATION. Admin must set the yearly rental before activating this plan.",
                            IsActive = false,
                            Kind = "StdRental",
                            LocalCallRatePerMinute = 0.60m,
                            MobileMessagingRatePerMinute = 1.25m,
                            Name = "Landline STD Yearly",
                            Price = 0m,
                            SecurityDeposit = 250m,
                            StdCallRatePerMinute = 1.75m,
                            ValidityMonths = 12
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PurchasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReorderLevel")
                        .HasColumnType("int");

                    b.Property<decimal>("ReplacementCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Products_Name");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("UX_Products_Sku");

                    b.HasIndex("VendorId");

                    b.ToTable("Products", null, t =>
                        {
                            t.HasCheckConstraint("CK_Products_Category_Values", "[Category] IN ('Modem', 'Router', 'Other')");

                            t.HasCheckConstraint("CK_Products_Prices_NonNegative", "[PurchasePrice] >= 0 AND [ReplacementCharge] >= 0");

                            t.HasCheckConstraint("CK_Products_Stock_NonNegative", "[StockQuantity] >= 0 AND [ReorderLevel] >= 0");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.ProductPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("RecordedByEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("SupplierReference")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("PurchaseDate");

                    b.HasIndex("RecordedByEmployeeId");

                    b.HasIndex("VendorId");

                    b.ToTable("ProductPurchases", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProductPurchases_Positive", "[Quantity] > 0 AND [UnitPrice] >= 0 AND [AmountPaid] >= 0 AND [AmountPaid] <= [Quantity] * [UnitPrice]");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.RetailShop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CityId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_RetailShops_City_Name");

                    b.ToTable("RetailShops", (string)null);
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_CustomerId")
                        .HasFilter("[CustomerId] IS NOT NULL");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_EmployeeId")
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Username");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_OneOwner", "([EmployeeId] IS NOT NULL AND [CustomerId] IS NULL) OR ([EmployeeId] IS NULL AND [CustomerId] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Vendors_Name");

                    b.ToTable("Vendors", (string)null);
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Bill", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Connection", "Connection")
                        .WithMany("Bills")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "GeneratedByEmployee")
                        .WithMany()
                        .HasForeignKey("GeneratedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Connection");

                    b.Navigation("GeneratedByEmployee");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Connection", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "CreatedByEmployee")
                        .WithMany()
                        .HasForeignKey("CreatedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Customer", "Customer")
                        .WithMany("Connections")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Connection", "LandlineConnection")
                        .WithMany()
                        .HasForeignKey("LandlineConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Order", "Order")
                        .WithMany("Connections")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Plan", "Plan")
                        .WithMany("Connections")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CreatedByEmployee");

                    b.Navigation("Customer");

                    b.Navigation("LandlineConnection");

                    b.Navigation("Order");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.ConnectionProduct", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Connection", "Connection")
                        .WithMany("ConnectionProducts")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Product", "Product")
                        .WithMany("ConnectionProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Connection");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Customer", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.City", "City")
                        .WithMany("Customers")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Employee", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.RetailShop", "RetailShop")
                        .WithMany("Employees")
                        .HasForeignKey("RetailShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RetailShop");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.FeasibilityCheck", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "CheckedByEmployee")
                        .WithMany()
                        .HasForeignKey("CheckedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Order", "Order")
                        .WithMany("FeasibilityChecks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CheckedByEmployee");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Feedback", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Connection", "Connection")
                        .WithMany("Feedbacks")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Customer", "Customer")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Connection");

                    b.Navigation("Customer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Order", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.DiscountScheme", "DiscountScheme")
                        .WithMany("Orders")
                        .HasForeignKey("DiscountSchemeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "PlacedByEmployee")
                        .WithMany()
                        .HasForeignKey("PlacedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Plan", "Plan")
                        .WithMany("Orders")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.RetailShop", "RetailShop")
                        .WithMany("Orders")
                        .HasForeignKey("RetailShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("DiscountScheme");

                    b.Navigation("PlacedByEmployee");

                    b.Navigation("Plan");

                    b.Navigation("RetailShop");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Payment", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Bill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "ReceivedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReceivedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.RetailShop", "RetailShop")
                        .WithMany()
                        .HasForeignKey("RetailShopId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("ReceivedByEmployee");

                    b.Navigation("RetailShop");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Product", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Vendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.ProductPurchase", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "RecordedByEmployee")
                        .WithMany()
                        .HasForeignKey("RecordedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RecordedByEmployee");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.RetailShop", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.City", "City")
                        .WithMany("RetailShops")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.User", b =>
                {
                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Customer", "Customer")
                        .WithOne("User")
                        .HasForeignKey("NexusServiceMarketingSystem.Models.Entities.User", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusServiceMarketingSystem.Models.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("NexusServiceMarketingSystem.Models.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Bill", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.City", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("RetailShops");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Connection", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("ConnectionProducts");

                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Customer", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Feedbacks");

                    b.Navigation("Orders");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.DiscountScheme", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Employee", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Order", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("FeasibilityChecks");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Plan", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Product", b =>
                {
                    b.Navigation("ConnectionProducts");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.RetailShop", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("NexusServiceMarketingSystem.Models.Entities.Vendor", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
