using Microsoft.AspNetCore.Mvc.ModelBinding;
using NexusServiceMarketingSystem.Models.Common;
using NexusServiceMarketingSystem.Models.Enums;

namespace NexusServiceMarketingSystem.Models.Entities
{
    /// <summary>
    /// A request for one or more connections of a single type, placed by a retail employee.
    /// The <see cref="OrderNumber"/> is generated by the system and can never be typed in.
    /// </summary>
    public class Order
    {
        public int Id { get; set; }

        /// <summary>
        /// System-generated, exactly 11 characters: D/B/T + 10-digit serial (e.g. D0000000001).
        /// The setter is private and <see cref="BindNeverAttribute"/> keeps it out of model binding,
        /// so it can only be set through <see cref="AssignOrderNumber"/> (called by the identifier generator).
        /// </summary>
        [BindNever]
        public string OrderNumber { get; private set; } = string.Empty;

        public int CustomerId { get; set; }
        public Customer Customer { get; set; } = null!;

        /// <summary>D / B / T. Must match the first letter of <see cref="OrderNumber"/>.</summary>
        public ConnectionType ConnectionType { get; set; }

        public int PlanId { get; set; }
        public Plan Plan { get; set; } = null!;

        /// <summary>
        /// Dial-up orders only: the landline plan chosen when the customer applies for the telephone
        /// line AND the dial-up internet together (no Nexus landline yet). Null for every other order.
        /// Both a landline and an internet feasibility check are run, and provisioning creates the
        /// telephone connection first and links the dial-up connection to it.
        /// </summary>
        public int? LandlinePlanId { get; set; }
        public Plan? LandlinePlan { get; set; }

        /// <summary>City where the connection is to be installed (feeds the account ID city code).</summary>
        public int CityId { get; set; }
        public City City { get; set; } = null!;

        public string InstallationAddress { get; set; } = string.Empty;

        /// <summary>How many connections are requested (bulk schemes depend on this). At least 1.</summary>
        public int Quantity { get; set; } = 1;

        /// <summary>The retail shop where staff placed the order; null for customer self-service.</summary>
        public int? RetailShopId { get; set; }
        public RetailShop? RetailShop { get; set; }

        /// <summary>The retail employee who placed the order; null for customer self-service.</summary>
        public int? PlacedByEmployeeId { get; set; }
        public Employee? PlacedByEmployee { get; set; }

        /// <summary>Bulk scheme applied to this order, if any.</summary>
        public int? DiscountSchemeId { get; set; }
        public DiscountScheme? DiscountScheme { get; set; }

        /// <summary>Discount percentage frozen at order time (so later scheme edits do not change old orders).</summary>
        public decimal DiscountPercent { get; set; }

        public OrderStatus Status { get; set; } = OrderStatus.Placed;

        /// <summary>Set by the database (UTC) when the order is inserted.</summary>
        public DateTime PlacedAtUtc { get; set; }

        /// <summary>Set by the database on insert; the application updates it whenever the status changes.</summary>
        public DateTime StatusChangedAtUtc { get; set; }

        public string? Remarks { get; set; }

        /// <summary>Concurrency token.</summary>
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        public ICollection<FeasibilityCheck> FeasibilityChecks { get; set; } = new List<FeasibilityCheck>();
        public ICollection<Connection> Connections { get; set; } = new List<Connection>();

        /// <summary>
        /// Assigns the generated order number. Allowed exactly once, only for a well-formed value
        /// whose first letter matches <see cref="ConnectionType"/>. Internal on purpose: only the
        /// identifier generator service calls it.
        /// </summary>
        internal void AssignOrderNumber(string orderNumber)
        {
            if (OrderNumber.Length != 0)
            {
                throw new InvalidOperationException("The order number has already been assigned and cannot be changed.");
            }

            if (!IdentifierFormat.IsValidOrderNumber(orderNumber))
            {
                throw new ArgumentException("Not a valid order number (expected D/B/T followed by 10 digits).", nameof(orderNumber));
            }

            if (orderNumber[0] != ConnectionType.ToCode())
            {
                throw new ArgumentException("The order number letter does not match the order's connection type.", nameof(orderNumber));
            }

            OrderNumber = orderNumber;
        }
    }
}
