using Microsoft.AspNetCore.Mvc.ModelBinding;
using NexusServiceMarketingSystem.Models.Common;
using NexusServiceMarketingSystem.Models.Enums;

namespace NexusServiceMarketingSystem.Models.Entities
{
    /// <summary>
    /// A connection actually provided to a customer after the order was found feasible.
    /// Its <see cref="AccountId"/> is generated by the system and can never be typed in.
    /// </summary>
    public class Connection
    {
        public int Id { get; set; }

        /// <summary>
        /// System-generated, exactly 16 characters: D/B/T + 3-digit city code + 12-digit serial.
        /// Private setter + BindNever: only <see cref="AssignAccountId"/> can set it.
        /// </summary>
        [BindNever]
        public string AccountId { get; private set; } = string.Empty;

        public int OrderId { get; set; }
        public Order Order { get; set; } = null!;

        public int CustomerId { get; set; }
        public Customer Customer { get; set; } = null!;

        /// <summary>The plan currently on the connection (customers can change plan).</summary>
        public int PlanId { get; set; }
        public Plan Plan { get; set; } = null!;

        /// <summary>D / B / T. Must match the first letter of <see cref="AccountId"/>.</summary>
        public ConnectionType ConnectionType { get; set; }

        /// <summary>City of installation; its code is characters 2-4 of the account ID.</summary>
        public int CityId { get; set; }
        public City City { get; set; } = null!;

        public string InstallationAddress { get; set; } = string.Empty;

        /// <summary>Telephone number, for Telephone (landline) connections.</summary>
        public string? PhoneNumber { get; set; }

        /// <summary>A dial-up connection requires a Nexus landline; this links to it.</summary>
        public int? LandlineConnectionId { get; set; }
        public Connection? LandlineConnection { get; set; }

        public ConnectionStatus Status { get; set; } = ConnectionStatus.Active;

        /// <summary>Security deposit charged for this connection after any bulk discount.</summary>
        public decimal SecurityDepositAmount { get; set; }

        /// <summary>Technical employee who created the connection.</summary>
        public int CreatedByEmployeeId { get; set; }
        public Employee CreatedByEmployee { get; set; } = null!;

        /// <summary>Set by the database (UTC) when the connection is created.</summary>
        public DateTime ActivatedAtUtc { get; set; }

        /// <summary>Set by the database on insert; the application updates it on every status change.</summary>
        public DateTime StatusChangedAtUtc { get; set; }

        /// <summary>Concurrency token.</summary>
        public byte[] RowVersion { get; set; } = Array.Empty<byte>();

        public ICollection<ConnectionProduct> ConnectionProducts { get; set; } = new List<ConnectionProduct>();
        public ICollection<Bill> Bills { get; set; } = new List<Bill>();
        public ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

        /// <summary>
        /// Assigns the generated account ID. Allowed exactly once, only for a well-formed value
        /// whose letter matches <see cref="ConnectionType"/> and whose city code matches the
        /// connection's city. Internal on purpose: only the identifier generator calls it.
        /// </summary>
        /// <param name="accountId">The 16-character account ID.</param>
        /// <param name="expectedCityCode">The code of this connection's city, used to cross-check characters 2-4.</param>
        internal void AssignAccountId(string accountId, string expectedCityCode)
        {
            if (AccountId.Length != 0)
            {
                throw new InvalidOperationException("The account ID has already been assigned and cannot be changed.");
            }

            if (!IdentifierFormat.IsValidAccountId(accountId))
            {
                throw new ArgumentException("Not a valid account ID (expected D/B/T, 3 city digits, 12 serial digits).", nameof(accountId));
            }

            if (accountId[0] != ConnectionType.ToCode())
            {
                throw new ArgumentException("The account ID letter does not match the connection type.", nameof(accountId));
            }

            if (IdentifierFormat.GetCityCode(accountId) != expectedCityCode)
            {
                throw new ArgumentException("The account ID city code does not match the connection's city.", nameof(accountId));
            }

            AccountId = accountId;
        }
    }
}
